apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: kimochi-repo
  namespace: flux-system
spec:
  interval: 10m
  url: https://github.com/jonhor/kimochi
  ref:
    branch: main
  ignore: |
    # exclude all
    /*
    # include Helm directory
    !/helm/  