# Verifies and builds the app image and makes it available locally.
# The helm chart is also verified and installed in a local kind cluster using the previously built image.
# Based on the example workflow from https://github.com/helm/chart-testing-action

name: Pull Request Checks

on: pull_request
  
jobs:
  build-and-lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Validate build configuration
        uses: docker/build-push-action@v6
        with:
          context: ./website
          file: ./website/Dockerfile
          call: check

      - name: Build and load image
        uses: docker/build-push-action@v4
        with:
          context: ./website
          file: ./website/Dockerfile
          push: false
          load: true
          tags: kimochi:${{ github.sha}}

      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: '3.18.4' 

      - name: Set up Python
        uses: actions/setup-python@v5.3.0
        with:
          python-version: '3.x'
          check-latest: true

      - name: Set up chart-testing (ct)
        uses: helm/chart-testing-action@v2.7.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: Run chart-testing (lint)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.12.0

      - name: Run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true'
        run: ct install --target-branch ${{ github.event.repository.default_branch }} --helm-extra-set-args "--set image.repository=kimochi --set image.tag=${{ github.sha }}"
